import React, { useCallback, useEffect, useRef, useState } from 'react';
import PostFeed from "@/components/feed/PostFeed";
import { API_CONFIG } from '@/config/apiConfig';
import httpClient from '@/lib/httpClient';
import { useAuth } from '@/hooks/useAuth';
import getInitials from '@/utils/getInitials';
import { useLocation } from 'react-router-dom';

const PAGE_SIZE = 20;

const Home = () => {
    const { isAuthenticated, isAuthInitialized, user } = useAuth();
    const location = useLocation();
    const emailSearch = typeof location.state?.emailSearch === 'string'
        ? location.state.emailSearch.trim()
        : '';
    const queryKey = emailSearch || '__home_feed__';
    const [pages, setPages] = useState([]);
    const [isLoading, setIsLoading] = useState(true);
    const [isLoadingMore, setIsLoadingMore] = useState(false);
    const [hasMore, setHasMore] = useState(false);
    const [error, setError] = useState('');
    const [loadMoreError, setLoadMoreError] = useState('');
    const bottomSentinelRef = useRef(null);
    const pagesRef = useRef(pages);
    const nextPageRef = useRef(1);
    const loadingPagesRef = useRef(new Set());
    const isMountedRef = useRef(false);
    const queryKeyRef = useRef(queryKey);
    pagesRef.current = pages;

    const loadPosts = useCallback(async (page, direction = 'next') => {
        const requestKey = emailSearch || '__home_feed__';
        const pageKey = `${requestKey}:${page}`;
        if (loadingPagesRef.current.has(pageKey) || pagesRef.current.some((group) => group.queryKey === requestKey && group.page === page)) return;
        loadingPagesRef.current.add(pageKey);

        if (direction === 'initial') {
            setIsLoading(true);
            setError('');
        } else {
            setIsLoadingMore(true);
            setLoadMoreError('');
        }

        try {
            const endpoint = emailSearch
                ? API_CONFIG.ENDPOINTS.HOME_POSTS_BY_EMAIL
                : API_CONFIG.ENDPOINTS.HOME;
            const params = new URLSearchParams({
                pageNo: String(page),
                pageSize: String(PAGE_SIZE),
            });
            if (emailSearch) params.set('email', emailSearch);

            const response = await httpClient.request(
                `${endpoint}?${params}`,
                { method: 'GET' }
            );
            if (!isMountedRef.current || queryKeyRef.current !== requestKey) return;

            const apiPosts = Array.isArray(response?.data) ? response.data : [];
            const mappedPosts = apiPosts.map((post) => {
                const body = post.autoGeneratedPostByAi || post.autoGeneratedPost || '';
                const articleBody = post.title && body.trimStart().startsWith(post.title)
                    ? body.trimStart().slice(post.title.length).trimStart()
                    : body;
                return {
                    id: post.id,
                    author: { name: post.author || 'Anonymous' },
                    timestamp: post.postedOn,
                    content: {
                        title: post.title,
                        html: articleBody,
                    },
                    likes: post.likeCount || 0,
                    comments: post.commentCount || 0,
                    shares: 0,
                    commentsList: null,
                    isLiked: Boolean(post.isLiked),
                };
            });

            setPages((currentPages) => currentPages.some((group) => group.queryKey === requestKey && group.page === page)
                ? currentPages
                : [...currentPages, { page, queryKey: requestKey, posts: mappedPosts }]);

            if (page === nextPageRef.current) {
                nextPageRef.current = page + 1;
                setHasMore(Boolean(response?.hasNext));
            }
        } catch (requestError) {
            if (isMountedRef.current && queryKeyRef.current === requestKey) {
                const message = requestError.message || 'Unable to load posts.';
                if (direction === 'initial') setError(message);
                else setLoadMoreError(message);
            }
        } finally {
            loadingPagesRef.current.delete(pageKey);
            if (isMountedRef.current && queryKeyRef.current === requestKey) {
                if (direction === 'initial') setIsLoading(false);
                else setIsLoadingMore(false);
            }
        }
    }, [emailSearch]);

    const currentUserName = isAuthenticated ? user?.userName || user?.email || '' : '';
    const currentUser = {
        name: currentUserName,
        initials: getInitials(currentUserName),
    };

    const loadNextPage = useCallback(() => loadPosts(nextPageRef.current), [loadPosts]);

    useEffect(() => {
        if (!isAuthInitialized) return undefined;
        isMountedRef.current = true;
        queryKeyRef.current = queryKey;
        loadingPagesRef.current.clear();
        nextPageRef.current = 1;
        pagesRef.current = [];
        setPages([]);
        setHasMore(false);
        setError('');
        setLoadMoreError('');
        loadPosts(1, 'initial');
        return () => {
            isMountedRef.current = false;
        };
    }, [isAuthInitialized, loadPosts, queryKey]);

    useEffect(() => {
        const sentinel = bottomSentinelRef.current;
        if (!sentinel || !hasMore || isLoading || isLoadingMore || error || loadMoreError) return;
        if (typeof IntersectionObserver === 'undefined') return;

        const observer = new IntersectionObserver(([entry]) => {
            if (entry.isIntersecting) loadNextPage();
        }, { rootMargin: '400px 0px' });

        observer.observe(sentinel);
        return () => observer.disconnect();
    }, [error, hasMore, isLoading, isLoadingMore, loadMoreError, loadNextPage]);

    return (
        <div className="home-page">
            <div className="w-full max-w-3xl mx-auto px-0 sm:px-2">
                {emailSearch && (
                    <h1 className="mb-4 text-lg font-semibold text-gray-800">
                        Posts by {emailSearch}
                    </h1>
                )}
                {isLoading ? (
                    <p role="status" className="py-6 text-center text-gray-500">Loading posts...</p>
                ) : error ? (
                    <div className="py-6 text-center">
                        <p role="alert" className="text-red-600">{error}</p>
                        <button className="mt-3 text-sm font-semibold text-[var(--app-brand)] underline" onClick={() => loadPosts(1, 'initial')}>
                            Try again
                        </button>
                    </div>
                ) : (
                    <>
                        {emailSearch && pages.every((group) => group.posts.length === 0) && (
                            <p className="py-6 text-center text-gray-500">No posts found for this email.</p>
                        )}
                        <PostFeed
                            pages={pages}
                            currentUser={currentUser}
                            onShare={(postId) => console.log(`Shared post ${postId}`)}
                            onAddOption={(postId) => console.log(`Options clicked for post ${postId}`)}
                        />
                        {loadMoreError && (
                            <div className="py-4 text-center">
                                <p role="alert" className="text-sm text-red-600">{loadMoreError}</p>
                                <button className="mt-2 text-sm font-semibold text-[var(--app-brand)] underline" onClick={loadNextPage}>
                                    Try again
                                </button>
                            </div>
                        )}
                        {isLoadingMore && (
                            <p role="status" className="py-4 text-center text-sm text-gray-500">Loading more posts...</p>
                        )}
                        {hasMore && <div ref={bottomSentinelRef} className="h-px" aria-hidden="true" />}
                        {hasMore && !loadMoreError && (
                            <div className="py-4 text-center">
                                <button
                                    type="button"
                                    className="rounded-md border border-[var(--app-brand)] px-4 py-2 text-sm font-semibold text-[var(--app-brand)] disabled:cursor-wait disabled:opacity-60"
                                    onClick={loadNextPage}
                                    disabled={isLoadingMore}
                                >
                                    {isLoadingMore ? 'Loading posts...' : 'Load more posts'}
                                </button>
                            </div>
                        )}
                    </>
                )}
            </div>
        </div>
    );
};

export default Home;