import React, { useCallback, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import { useDispatch, useSelector } from 'react-redux';
import PostFeed from '../components/feed/PostFeed';
import { fetchMyPosts } from '@/store/slices/profileSlice';

const PAGE_SIZE = 20;

const MyPosts = () => {
  const dispatch = useDispatch();
  const {
    myPosts: response,
    isLoadingMyPosts,
    isLoadingMoreMyPosts,
    myPostsError,
    myPostsMoreError,
  } = useSelector((state) => state.profile);
  const bottomSentinelRef = useRef(null);
  const nextPageRef = useRef(2);
  const loadingMoreRef = useRef(false);
  const posts = (Array.isArray(response?.data) ? response.data : []).map((post) => {
    const body = post.autoGeneratedPostByAi || post.autoGeneratedPost || '';
    const articleBody = post.title && body.trimStart().startsWith(post.title)
      ? body.trimStart().slice(post.title.length).trimStart()
      : body;

    return {
      id: post.id,
      author: { name: post.author || 'Anonymous' },
      timestamp: post.postedOn,
      content: { title: post.title, html: articleBody },
      likes: post.likeCount || 0,
      comments: post.commentCount || 0,
      shares: 0,
      commentsList: null,
      isLiked: Boolean(post.isLiked),
    };
  });

  useEffect(() => {
    nextPageRef.current = 2;
    dispatch(fetchMyPosts({ pageNo: 1, pageSize: PAGE_SIZE }));
  }, [dispatch]);

  const handleRetry = () => {
    nextPageRef.current = 2;
    dispatch(fetchMyPosts({ pageNo: 1, pageSize: PAGE_SIZE }));
  };

  const loadNextPage = useCallback(async () => {
    if (loadingMoreRef.current || isLoadingMyPosts || !response?.hasNext) return;

    loadingMoreRef.current = true;
    const pageNo = nextPageRef.current;
    try {
      const result = await dispatch(fetchMyPosts({ pageNo, pageSize: PAGE_SIZE }));
      if (fetchMyPosts.fulfilled.match(result)) nextPageRef.current = pageNo + 1;
    } finally {
      loadingMoreRef.current = false;
    }
  }, [dispatch, isLoadingMyPosts, response?.hasNext]);

  useEffect(() => {
    const sentinel = bottomSentinelRef.current;
    if (!sentinel || !response?.hasNext || isLoadingMyPosts || isLoadingMoreMyPosts || myPostsMoreError) return;
    if (typeof IntersectionObserver === 'undefined') return;

    const observer = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting) loadNextPage();
    }, { rootMargin: '400px 0px' });

    observer.observe(sentinel);
    return () => observer.disconnect();
  }, [isLoadingMoreMyPosts, isLoadingMyPosts, loadNextPage, myPostsMoreError, response?.hasNext]);

  return (
    <main className="myposts-page">
      <header className="myposts-page__header">
        <div className="myposts-page__heading">
          <p className="myposts-page__eyebrow">Your publishing</p>
          <h1>My Posts</h1>
          <p className="myposts-page__subtitle">Your posts, gathered in one place.</p>
        </div>
        <div className="myposts-page__actions">
          <span className="myposts-page__count" aria-label={`${posts.length} posts`}>
            <strong>{isLoadingMyPosts ? '...' : response?.count ?? posts.length}</strong>
            <span>posts</span>
          </span>
          <Link to="/profile" aria-label="Back to profile" title="Back to profile">
          <ArrowLeft size={18} />
          </Link>
        </div>
      </header>
      {isLoadingMyPosts && !response && <p className="myposts-page__state" role="status">Loading your posts...</p>}
      {myPostsError && (
        <div className="my-posts-error">
          <p role="alert">{myPostsError}</p>
          <button type="button" onClick={handleRetry}>Try again</button>
        </div>
      )}
      {response && !myPostsError && (
        <>
          <PostFeed posts={posts} openPostsInNewTab emptyMessage="No posts published yet." />
          {myPostsMoreError && (
            <div className="py-4 text-center">
              <p role="alert" className="text-sm text-red-600">{myPostsMoreError}</p>
              <button type="button" className="mt-2 text-sm font-semibold text-[var(--app-brand)] underline" onClick={loadNextPage}>
                Try again
              </button>
            </div>
          )}
          {isLoadingMoreMyPosts && <p role="status" className="py-4 text-center text-sm text-gray-500">Loading more posts...</p>}
          {response.hasNext && <div ref={bottomSentinelRef} className="h-px" aria-hidden="true" />}
          {response.hasNext && !myPostsMoreError && (
            <div className="py-4 text-center">
              <button
                type="button"
                className="rounded-md border border-[var(--app-brand)] px-4 py-2 text-sm font-semibold text-[var(--app-brand)] disabled:cursor-wait disabled:opacity-60"
                onClick={loadNextPage}
                disabled={isLoadingMoreMyPosts}
              >
                {isLoadingMoreMyPosts ? 'Loading posts...' : 'Load more posts'}
              </button>
            </div>
          )}
        </>
      )}
    </main>
  );
};

export default MyPosts;