import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Search, ArrowUpRight } from 'lucide-react';
import { API_CONFIG } from '@/config/apiConfig';
import httpClient from '@/lib/httpClient';
import '../styles/SearchPosts.css';

const searchOptions = [
  { value: 'all', label: 'All fields' },
  { value: 'author', label: 'Author' },
  { value: 'title', label: 'Title' },
  { value: 'source', label: 'Source' },
];

function SearchPosts() {
  const [searchParams, setSearchParams] = useSearchParams();
  const [query, setQuery] = useState(searchParams.get('q') || '');
  const [searchBy, setSearchBy] = useState(searchParams.get('by') || 'all');
  const [results, setResults] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const [hasSearched, setHasSearched] = useState(false);

  const handleSearch = async (event) => {
    event.preventDefault();
    const term = query.trim();
    if (!term) {
      setResults([]);
      setHasSearched(false);
      setError('Enter a name, title, or source to search.');
      return;
    }

    setIsLoading(true);
    setError('');
    setHasSearched(true);
    setSearchParams({ q: term, by: searchBy });

    try {
      const params = new URLSearchParams({ query: term, searchBy, pageNo: '1', pageSize: '20' });
      const response = await httpClient.request(`${API_CONFIG.ENDPOINTS.HOME}/search?${params}`);
      setResults(Array.isArray(response?.data) ? response.data : []);
    } catch (requestError) {
      setError(requestError.message || 'Search is temporarily unavailable.');
      setResults([]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <main className="search-page">
      <header className="search-page__header">
        <p className="search-page__eyebrow">Explore the feed</p>
        <h1>Find a post</h1>
        <p>Search by author, title, source, or across all post details.</p>
      </header>

      <form className="search-form" onSubmit={handleSearch}>
        <label className="search-form__query">
          <span className="sr-only">Search posts</span>
          <Search size={19} aria-hidden="true" />
          <input
            type="search"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Search posts, people, topics..."
          />
        </label>
        <label className="search-form__filter">
          <span className="sr-only">Search within</span>
          <select value={searchBy} onChange={(event) => setSearchBy(event.target.value)}>
            {searchOptions.map((option) => (
              <option key={option.value} value={option.value}>{option.label}</option>
            ))}
          </select>
        </label>
        <button className="search-form__submit" type="submit" disabled={isLoading} aria-label="Search">
          <Search size={18} />
        </button>
      </form>

      <section className="search-results" aria-live="polite">
        {error && <p className="search-results__message search-results__message--error" role="alert">{error}</p>}
        {isLoading && <p className="search-results__message">Searching posts...</p>}
        {!isLoading && !error && hasSearched && results.length === 0 && (
          <p className="search-results__message">No posts matched that search.</p>
        )}
        {!isLoading && results.length > 0 && (
          <>
            <p className="search-results__count">{results.length} results</p>
            {results.map((post) => {
              const body = post.autoGeneratedPostByAi || post.autoGeneratedPost || '';
              return (
                <Link className="search-result" to={`/post/${post.id}`} key={post.id}>
                  <div className="search-result__meta">
                    <span>{post.author || 'PostIQ member'}</span>
                    <time dateTime={post.postedOn}>
                      {post.postedOn ? new Date(post.postedOn).toLocaleDateString() : ''}
                    </time>
                  </div>
                  <h2>{post.title || 'Untitled post'}</h2>
                  <p>{body || post.source || 'Open this post to read more.'}</p>
                  <div className="search-result__footer">
                    <span>{post.source || 'PostIQ'}</span>
                    <span className="search-result__open">Read post <ArrowUpRight size={15} /></span>
                  </div>
                </Link>
              );
            })}
          </>
        )}
      </section>
    </main>
  );
}

export default SearchPosts;