const HOME_API_URL = 'http://localhost:5121/api';
const USER_API_URL = 'http://localhost:5255/api';

export const fetchPosts = async (pageNo = 1, pageSize = 10) => {
  const response = await fetch(`${HOME_API_URL}/Home?pageNo=${pageNo}&pageSize=${pageSize}`);
  if (!response.ok) throw new Error('Failed to fetch posts');
  const result = await response.json();
  return result.data.map(post => ({
    id: post.id,
    author: {
      name: post.author || 'Anonymous',
      avatar: `https://i.pravatar.cc/48?u=${post.userId}`,
    },
    timestamp: post.postedOn,
    content: {
      title: post.title || null,
      text: post.autoGeneratedPost || post.autoGeneratedPostByAi || post.title,
      summary: post.autoGeneratedPostByAi || null,
    },
    likes: post.likeCount || 0,
    comments: post.commentCount || 0,
    shares: 0,
    commentsList: [],
  }));
};

export const fetchComments = async (postId) => {
  const response = await fetch(`${HOME_API_URL}/Home/${postId}/comments`);
  if (!response.ok) throw new Error('Failed to fetch comments');
  const result = await response.json();
  return (result.data || []).map(comment => ({
    id: comment.id,
    author: {
      name: `User ${comment.userId}`,
      avatar: `https://i.pravatar.cc/32?u=${comment.userId}`,
    },
    text: comment.content,
    timestamp: comment.createdOn,
    likes: comment.likeCount || 0,
  }));
};

export const likePost = async (postId, userId) => {
  const response = await fetch(`${HOME_API_URL}/Home/${postId}/like`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ postId, userId }),
  });
  if (!response.ok) throw new Error('Failed to like post');
  return await response.json();
};

export const commentPost = async (postId, userId, content) => {
  const response = await fetch(`${HOME_API_URL}/Home/${postId}/comment`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ postId, userId, content }),
  });
  if (!response.ok) throw new Error('Failed to comment on post');
  return await response.json();
};

export const likeComment = async (commentId, userId) => {
  const response = await fetch(`${HOME_API_URL}/Home/comment/${commentId}/like`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ commentId, userId }),
  });
  if (!response.ok) throw new Error('Failed to like comment');
  return await response.json();
};

export const replyToComment = async (postId, parentCommentId, userId, content) => {
  const response = await fetch(`${HOME_API_URL}/Home/${postId}/comment/${parentCommentId}/reply`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ postId, parentCommentId, userId, content }),
  });
  if (!response.ok) throw new Error('Failed to reply to comment');
  return await response.json();
};

export const createPost = async (userId, author, text) => {
  const response = await fetch(`${HOME_API_URL}/Home`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ userId, author, text }),
  });
  if (!response.ok) throw new Error('Failed to create post');
  const result = await response.json();
  return result.data; // returns the new post's long ID
};
